blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discord
    url: https://discord.com/invite/Z74UAQ5vPR
    about: You can discuss products and services on Discord, too!
#  - name: ðŸ“§ Support
#    url: mailto:support@theriversi.de
#    about: Errors relating to your account? Drop us an email!
